"""empty message

Revision ID: 6d9473d9a196
Revises: 
Create Date: 2025-08-11 00:26:16.384206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d9473d9a196'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('msg_id', sa.Integer(), autoincrement=True, nullable=False, comment='消息id'),
    sa.Column('session_id', sa.Integer(), nullable=True, comment='会话id'),
    sa.Column('sender_type', sa.String(length=9), nullable=True, comment='发送方类型(user/assistant)'),
    sa.Column('session_summary', sa.Text(), nullable=True, comment='会话摘要'),
    sa.Column('content', sa.Text(), nullable=True, comment='消息内容'),
    sa.Column('reference', sa.Text(), nullable=True, comment='参考信息（如果sender_type为assistant）'),
    sa.Column('first_token_time_ms', sa.Integer(), nullable=True, comment='首个token用时（毫秒）'),
    sa.Column('islike', sa.SmallInteger(), nullable=True, comment='是否点赞（0:无反馈，1:点赞，-1:点踩）'),
    sa.Column('feedback', sa.Text(), nullable=True, comment='反馈信息（如果islike为-1）'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('msg_id')
    )
    op.create_table('file_manage',
    sa.Column('manage_id', sa.Integer(), autoincrement=True, nullable=False, comment='管理id'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='文件名'),
    sa.Column('directory', sa.String(length=255), nullable=False, comment='所在目录'),
    sa.Column('operate_type', sa.SmallInteger(), nullable=True, comment='操作类型（1:添加, 0:删除）'),
    sa.Column('is_chunked', sa.SmallInteger(), nullable=True, comment='是否完成chunk划分（0:未完成, 1:已完成）(如果operate_type为1)'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('manage_id')
    )
    op.create_table('session_info',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False, comment='会话id'),
    sa.Column('session_summary', sa.Text(), nullable=True, comment='会话摘要'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户id'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('user_info',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False, comment='用户id'),
    sa.Column('user_name', sa.String(length=100), nullable=False, comment='用户昵称'),
    sa.Column('mobile', sa.String(length=16), nullable=False, comment='手机号'),
    sa.Column('is_admin', sa.SmallInteger(), nullable=True, comment='是否是管理员'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('mobile')
    )
    op.create_table('user_login',
    sa.Column('login_id', sa.Integer(), autoincrement=True, nullable=False, comment='登录id'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户id'),
    sa.Column('mobile', sa.String(length=16), nullable=False, comment='手机号'),
    sa.Column('mypassword', sa.String(length=16), nullable=False, comment='密码'),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('last_login_stamp', sa.Integer(), nullable=True, comment='最后登录时间戳'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('login_id'),
    sa.UniqueConstraint('mobile')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_login')
    op.drop_table('user_info')
    op.drop_table('session_info')
    op.drop_table('file_manage')
    op.drop_table('chat_message')
    # ### end Alembic commands ###
